### PR TITLE
[ISSUE #899]Fix the groupName takes the namespace prefix

### PR DESCRIPTION
**Pull request by zhangjidi2016**
## What is the purpose of the change

#899 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by caigy — CHANGES_REQUESTED** [review]
The name of consumer groups may be the same in different namespaces, so IMO it's necessary to keep the namespace.

**Comment by zhangjidi2016** [comment]
> The name of consumer groups may be the same in different namespaces, so IMO it's necessary to keep the namespace.

I don't think so. Firstly, namespace is a resource isolation to prevent topic or group names. For users, the topic or group without namespace is set in the client code, while adding namespace prefix to topic or group is handled in the program. The direct display of namespace prefix may cause confusion to the user. Secondly, other language clients such as Java remove the prefix of the above problems, which should be kept consistent.

**Comment by lizhanhui** [comment]
> Secondly, other language clients such as Java remove the prefix of the above problems, which should be kept consistent.

Agree. It's essential to maintain consistency among different bindings.

**Review by ShannonDing — APPROVED** [review]

**Comment by zongtanghu** [comment]
LGTM

**Pull request merged**
