### PR TITLE
[feat] fix query not found

### PR DESCRIPTION
**Pull request by aireet**
## What is the purpose of the change

when i start a new group to consume an old topic

i got some error logs
```
"[RocketMQ] msg: fetch offset of mq from broker error \n fields: map[MessageQueue:MessageQueue [topic=demo-topic, brokerName=broker-master, queueId=2] consumerGroup:rocketmq-EE10 underlayError:broker response code: 22, remarks: Not found, V3_0_6_SNAPSHOT maybe this group consumer boot first]"

"[RocketMQ] msg: do defaultConsumer, add a new mq failed \n fields: map[MessageQueue:MessageQueue [topic=demo-topic, brokerName=broker-master, queueId=2] consumerGroup:rocketmq-EE10]"}
```

then i find 
https://github.com/apache/rocketmq-client-go/blob/master/consumer/consumer.go:770

```
	lastOffset, err := dc.storage.readWithException(mq, _ReadFromStore)
	if err != nil {
		// 这里 lastOffset = -1
		return lastOffset, err
	}
```

if the broker query not found, program get an error, that will triggers this problem, and  dc.option.FromWhere  will never work

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by ShannonDing — APPROVED** [review]

**Comment by Cczzzz** [comment]
When will this feature be released?

**Comment by GrumpyCat0413** [comment]
I have the same problem，how to solve it?

**Comment by GrumpyCat0413** [comment]
> 

you can update  sdk version github.com/apache/rocketmq-client-go/v2 to upper >2.1.1

**Comment by ngyhd** [comment]
> > 
> 
> you can update sdk version github.com/apache/rocketmq-client-go/v2 to upper >2.1.1

我版本2.1.1还是有这个问题

**Comment by adamzhoul** [comment]
when will 2.2.0 plan to release?

**Pull request merged**
