### PR TITLE
[PanicFix] issue#1062 fix trace init nil pointer panic and clientid add group name at first

### PR DESCRIPTION
**Pull request by iGoogle-ink**
## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by iGoogle-ink** [comment]
fix #1062

**Comment by cserwen** [comment]
直接修改clientId影响的内容较多，可以参考下java sdk的实现逻辑，为轨迹producer设置不同的groupName来解决 @iGoogle-ink

**Comment by iGoogle-ink** [comment]
> 直接修改clientId影响的内容较多，可以参考下java sdk的实现逻辑，为轨迹producer设置不同的groupName来解决 @iGoogle-ink

你说的 producer 和 consumer 没问题，但是当使用 tracer 的时候，tracer 默认初始化的是固定的，没办法改，如果不改 clientid，可以考虑把 tracer 的初始化部分配置开放设置

**Comment by cserwen** [comment]
> > 直接修改clientId影响的内容较多，可以参考下java sdk的实现逻辑，为轨迹producer设置不同的groupName来解决 @iGoogle-ink
> 
> 你说的 producer 和 consumer 没问题，但是当使用 tracer 的时候，tracer 默认初始化的是固定的，没办法改，如果不改 clientid，可以考虑把 tracer 的初始化部分配置开放设置

参考 java SDK 的实现 https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java#L108

**Pull request closed without merging**
