### PR TITLE
Feat/resolver

### PR DESCRIPTION
**Pull request by vearne**
## What is the purpose of the change

In my scenario, my nameservers are hosts represented by a group of domain names. So I need a new resolver to resolve the nameservers.

## Brief changelog

add dns Resolver to resolve name server 

## Verifying this change

go test . -v --run TestDNSResolver

### CODE REVIEW

**Comment by xujianhai666** [comment]
fmt before pr agian. @vearne

**Comment by vearne** [comment]
ok

xujianhai666 <notifications@github.com> 于2020年11月26日周四 下午2:21写道：

**Comment by xujianhai666** [comment]
sorry for that I merge incorrectly, could pull request again with format "https://github.com/apache/rocketmq/wiki/RIP-14-RocketMQ-Community-Operation-Conventions"

**Comment by vearne** [comment]
> sorry for that I merge incorrectly, could pull request again with format "https://github.com/apache/rocketmq/wiki/RIP-14-RocketMQ-Community-Operation-Conventions"

Is something wrong in my comment?

**Comment by vearne** [comment]
@xujianhai666  Is something wrong in my comment?

**Pull request merged**
