### PR TITLE
[ISSUE #87] use goimport to fmt import order 

### PR DESCRIPTION
**Pull request by xujianhai666**
## What is the purpose of the change

Use goimports to fmt import order

## Brief changelog

Reimport import oder

### CODE REVIEW

**Comment by wenfengwang** [comment]
LGTM, @ShannonDing @zongtanghu @jonnxu, please merge the PR when CI success.

**Comment by wenfengwang** [comment]
@xujianhai666 please resolve conflict

**Comment by xujianhai666** [comment]
> @xujianhai666 please resolve conflict

done

**Comment by xujianhai666** [comment]
> @xujianhai666 please resolve conflict

@wenfengwang done

**Comment by wenfengwang** [comment]
LGTM

**Pull request merged**
