### PR TITLE
[ISSUE #95] Support multiple NameServe

### PR DESCRIPTION
**Pull request by xujianhai666**
## What is the purpose of the change

Support multiple NameServe

## Brief changelog

1. add Namesrv struct and some method
2. change Namesrv delivery instead of using env

### CODE REVIEW

**Comment by wenfengwang** [comment]
consider retry when getting router failed from a NameServer

**Comment by wenfengwang** [comment]
please resolve the conflict.

**Comment by xujianhai666** [comment]
> please resolve the conflict.

@wenfengwang  done

**Comment by wenfengwang** [comment]
LGTM, @ShannonDing @zongtanghu @jonnxu please merge the PR

**Pull request merged**
