### PR TITLE
[ISSUE #894](feat): add filter hooks in consumer.

### LINKED ISSUE #894: Add message filter extension hook
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Require user defined message filter hook before tracer and message processing to filter message by complex condition which cannot  be satisfied by SQL92/TAG filter.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
shoud-have

### PR DESCRIPTION
**Pull request by superhx**
## Add filter hooks to consumer

Developer can use filter hooks to filter pulled messages before message processing.

close #894

### CODE REVIEW

**Review by ShannonDing — COMMENTED** [review]
I am not sure what scenario this feature is used in. First of all, I think we can use tags to filter messages directly. If some messages do not need to be processed by the business, we can also directly return success when consuming.

**Comment by superhx** [comment]
> scenario this featu

1. Java SDK has the FilterMessageHook
2. Don't want send success consumed trace when message is filtered。

**Comment by lizhanhui** [comment]
It makes sense to have a business tier filter mechanism.

**Comment by lizhanhui** [comment]
@superhx One more thing, you may request this feature [here](https://github.com/apache/rocketmq-clients) too, where the next major version is being built.

**Review by ShannonDing — APPROVED** [review]

**Pull request merged**
